# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "886d0ccfb58406f52a8b5b4442707d08"
name = "testing app"
application_url = "https://duke-devoutly-appear.ngrok-free.dev"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://duke-devoutly-appear.ngrok-free.dev/shopify/callback"
]
